# Generated by Django 2.1.15 on 2020-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_medicine_price_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examfee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='precedure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AlterField(
            model_name='examfee',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precedure',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
